name: Java CI

on: [push]

jobs:
  build:
    env:
      MAVEN_OPTS: -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
      CI: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: airsquared/setup-java@master
        with:
          java-version: '1.8'
          javafx: true
      - name: Build with Maven
        run: mvn -B package --file pom.xml
